import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";

export default function ContributorBriefing() {
  return (
    <>
      <Navbar />
      <main className="flex-1">
        <section className="container mx-auto px-4 py-16">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl font-bold mb-4">For Contributors</h1>
            <p className="text-muted-foreground text-lg">
              Learn how to discover funded work, submit PRs, and earn rewards from yield generated by organization pools.
            </p>
          </div>
        </section>

        <section className="container mx-auto px-4 pb-16">
          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <Card>
              <CardHeader>
                <CardTitle>1. Connect & Verify</CardTitle>
                <CardDescription>Wallet + GitHub account</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Start by connecting your wallet and linking your GitHub. This lets projects attribute your work and route rewards.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>2. Find Funded Work</CardTitle>
                <CardDescription>Explore pools and issues</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Browse organization pools and funded tasks. Pick issues aligned with your skills and start contributing.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>3. Submit PRs & Earn</CardTitle>
                <CardDescription>Yield-based rewards</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Submit your PRs. As pools generate yield, rewards are distributed automatically based on contribution impact.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>

        <section className="container mx-auto px-4 pb-20">
          <div className="max-w-3xl mx-auto">
            <Card>
              <CardHeader>
                <CardTitle>What you get</CardTitle>
                <CardDescription>Aligned incentives for open-source work</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <ul className="list-disc pl-5 text-sm text-muted-foreground space-y-2">
                  <li>Access to funded tasks with transparent reward logic</li>
                  <li>Non-custodial payouts to your wallet (mocked in this demo)</li>
                  <li>Recognition tied to your GitHub identity</li>
                </ul>
                <div className="pt-4 flex flex-col sm:flex-row gap-3">
                  <Link href="/contributor/onboarding" className="w-full sm:w-auto">
                    <Button size="lg" className="w-full sm:w-auto">
                      Get Started
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Button>
                  </Link>
                  <Link href="/contributor/dashboard" className="w-full sm:w-auto">
                    <Button size="lg" variant="outline" className="w-full sm:w-auto">
                      View Dashboard
                    </Button>
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}


